apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
  - name: test-webserver
    image: registry.k8s.io/test-webserver:latest
  volumes:
  - name: mydir
    hostPath:
      # Ensure the file directory is created.
      path: /srv/app-config
