apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpathpv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostpath:
    path: /srv/app-config
