apiVersion: v1
kind: PersistentVolume
metadata:
  name: stsvol2
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-client
  mountOptions:
  nfs:
    path: /srv/nfs
    server: 192.168.11.4
